### ISSUE TITLE
Would be nice to have "apply plugin: 'clojure'" !

### ISSUE THREAD

**Issue by aadrian** [cursive-ide/gradle-clojure#1]
I know it's just esthetics,  but would be nice if there would
be something like:

``` groovy
apply plugin: 'kotlin'
apply plugin: 'groovy'
apply plugin: 'clojure'
apply plugin: 'clojure-script'
```

Thank you.

**Comment by cursive-ghost** [comment]
Actually, you can already do this, see the [plugin repo page](https://plugins.gradle.org/plugin/com.cursive-ide.clojure) for an example.

**Comment by cursive-ghost** [comment]
BTW if you look at the "About the new plugin mechanism..." link there, it talks about a variety of reasons why you might want to use the new-style syntax.

**Comment by aadrian** [comment]
I mean the short name, like it's possible for Java :) . Your example is using a "package" name.

**Comment by cursive-ghost** [comment]
Oh I see. Hmm, that might conflict with existing plugins (Clojuresque), although no-one will use the two together, I guess. I'm inclined to leave this to be honest, since it's a pretty minor cosmetic issue. If I get some time I'll investigate possible drawbacks to using the shorter name.
