### ISSUE TITLE
Building Clojure with gradle-clojure?

### ISSUE THREAD

**Issue by aadrian** [cursive-ide/gradle-clojure#15]
Hi,

would it be possible to to build Clojure itself with `gradle-clojure`?
https://github.com/clojure/clojure
(it's still built with ANT :( ).

I guess if it could work (and **if** it would be accepted :) ) , that would greatly expose `gradle-clojure` to the community.  

Thank you.

**Comment by cursive-ghost** [comment]
Clojure is currently built with Maven, and IMO that's *extremely* unlikely to change.

BTW as noted in the README, this repo is deprecated and the new plugin is over at [gradle-clojure](https://github.com/gradle-clojure). I'll close this issue.

**Comment by aadrian** [comment]
@cursive-ide sorry, just saw too late that I pasted in the wrong one.  

Read-only? https://github.com/blog/2460-archiving-repositories
