### ISSUE TITLE
testClojure in check vs test

### ISSUE THREAD

**Issue by pbzdyl** [cursive-ide/gradle-clojure#4]
`testClojure` task is added as dependency of `check` (`JavaBasePlugin.CHECK_TASK_NAME`) task rather than `test` (`JavaPlugin.TEST_TASK_NAME`).

I thought that unit tests should be executed as part of the `test` "phase" and understood `check` as a stage for integration tests, source code analysis etc. (checkstyle, findbugs).

What is the reason for such a choice and could it be changed?

**Comment by cursive-ghost** [comment]
It could definitely be changed if what it's doing is the wrong thing - I'm actually not that familiar with Gradle. I'm not sure what other test tool plugins do - I'll investigate this and fix it if it should be in the test phase.

**Comment by pbzdyl** [comment]
@cmf You mentioned in a PR comment that you will be releasing new version soon. Did you have a chance to take a look at `test` vs `check` phase for `testClojure`?

In our case (and I think it would be quite common) our Clojure tests are unit tests and it would be more convenient to have them run as part of `test` rather than `check`.

If this behaviour could be changed and included in the next release it would be great! 😄

**Comment by cursive-ghost** [comment]
Sure, I'll look at this too.

**Comment by pbzdyl** [comment]
@cmf Do you have any estimates when a new version of the plugin could be released? I would like to be clear that I am not trying to push you in any way but just assess if it would be worth to temporarily switch to version released privately by me.

**Comment by cursive-ghost** [comment]
@pbzdyl My apologies again for the delay. If I don't have too many EuroClojure beers I'll try to do this tonight.

However I investigated the test vs check issue. From what I can tell, all test integrations have are run as part of check, and test is not actually a lifecycle task designed to be used in this manner. In fact, you can see [here](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L138-L141) that test itself is run as part of check, and that definitely mentions unit tests. I don't want to change the default for this without understanding it better.

**Comment by pbzdyl** [comment]
Now when I look at it again, it actually seems correct to have Clojure tests be part of the `check` phase. Thanks!
