### ISSUE TITLE
JUnit report generation support in testClojure task

### ISSUE THREAD

**Issue by pbzdyl** [cursive-ide/gradle-clojure#5]
Would it be possible to extend `testClojure` task to support JUnit generation?

I could submit a PR adding such functionality but the question is if it would be considered at all before I start working on it.

**Comment by cursive-ghost** [comment]
Do you mean generating the JUnit XML output format? Yes, by all means, PR welcome.

**Comment by pbzdyl** [comment]
Yes, I meant JUnit XML output format. I have already submitted PR.

**Comment by pbzdyl** [comment]
Done in PR #6.
